# Generated by Django 6.0.5 on 2026-06-09 07:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('evento_nombre', models.CharField(max_length=200)),
                ('nombre_completo', models.CharField(max_length=200)),
                ('num_asistentes', models.IntegerField()),
                ('zona', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254)),
                ('asistio', models.BooleanField(default=False)),
                ('fecha_reserva', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
