# Generated by Django 6.0.5 on 2026-06-10 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria_app', '0002_reserva'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.PositiveSmallIntegerField()),
                ('details', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/')),
                ('CategoryEvents', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafeteria_app.categoryevents')),
            ],
        ),
    ]
