# Generated by Django 4.2.30 on 2026-06-15 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria_app', '0002_reserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_best',
            field=models.BooleanField(default=False, verbose_name='mas queridos'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_new',
            field=models.BooleanField(default=False, verbose_name='menu nuevo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
