# Generated by Django 6.0.5 on 2026-06-10 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria_app', '0003_categoryevents_events'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='price',
        ),
    ]
