# Generated by Django 6.0.5 on 2026-06-12 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria_app', '0004_remove_events_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='imageevents/')),
            ],
        ),
        migrations.DeleteModel(
            name='Reserva',
        ),
    ]
