# Generated by Django 6.0.5 on 2026-06-13 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria_app', '0005_imagenevents_delete_reserva'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlimentoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='alimentos/')),
                ('es_promocion', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alimentos', to='cafeteria_app.events')),
            ],
        ),
        migrations.DeleteModel(
            name='ImagenEvents',
        ),
    ]
