# Generated by Django 4.2.30 on 2026-06-15 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria_app', '0003_product_is_best_product_is_new_alter_product_price'),
        ('cafeteria_app', '0007_reserva'),
    ]

    operations = [
    ]
