# Generated by Django 6.0.5 on 2026-06-16 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria_app', '0008_merge_20260615_0208'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reserva',
        ),
    ]
