# Generated by Django 6.0.5 on 2026-06-16 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria_app', '0009_delete_reserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='details_min',
            field=models.TextField(blank=True),
        ),
    ]
