# Generated by Django 4.2.30 on 2026-06-19 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria_app', '0012_pedido_pedidoitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExclusiveFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='alimentos/')),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('target_food', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cafeteria_app.exclusivefood')),
            ],
        ),
        migrations.RenameField(
            model_name='events',
            old_name='details',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='events',
            name='details_min',
        ),
        migrations.AlterField(
            model_name='events',
            name='CategoryEvents',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='cafeteria_app.categoryevents'),
        ),
        migrations.DeleteModel(
            name='AlimentoEvento',
        ),
        migrations.AddField(
            model_name='exclusivefood',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exclusive', to='cafeteria_app.events'),
        ),
    ]
