# Generated by Django 4.2.30 on 2026-06-23 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria_app', '0013_exclusivefood_promotion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageProduct', models.ImageField(upload_to='galeria_producto/')),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='cafeteria_app.product')),
            ],
        ),
    ]
