# Generated by Django 4.2.30 on 2026-06-23 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria_app', '0014_imagenproducto'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fin del evento'),
        ),
        migrations.AddField(
            model_name='events',
            name='fecha_inicio',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Inicio del evento'),
        ),
    ]
