# Generated by Django 6.0.6 on 2026-06-24 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria_app', '0015_events_fecha_fin_events_fecha_inicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='descuento',
            field=models.IntegerField(default=0, verbose_name='Descuento'),
        ),
    ]
