# Generated by Django 4.2.30 on 2026-06-24 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria_app', '0015_events_fecha_fin_events_fecha_inicio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagenproducto',
            old_name='event',
            new_name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0, verbose_name='Stock disponible'),
        ),
        migrations.AlterField(
            model_name='exclusivefood',
            name='precio',
            field=models.PositiveIntegerField(),
        ),
    ]
