# Generated by Django 4.2.30 on 2026-06-24 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria_app', '0016_rename_event_imagenproducto_product_product_stock_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banners/')),
                ('texto_boton', models.CharField(blank=True, max_length=30, verbose_name='Texto del botón')),
                ('link', models.CharField(blank=True, max_length=200, verbose_name='Enlace del botón')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden de aparición')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
    ]
