# Generated by Django 4.2.30 on 2026-06-24 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria_app', '0018_banner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagenevento',
            options={'ordering': ['orden']},
        ),
        migrations.AddField(
            model_name='imagenevento',
            name='orden',
            field=models.PositiveIntegerField(default=0, verbose_name='Orden de aparición'),
        ),
        migrations.AlterField(
            model_name='exclusivefood',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='imagenevento',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
    ]
