# Generated by Django 4.2.30 on 2026-06-26 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria_app', '0019_alter_imagenevento_options_imagenevento_orden_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promotion',
            options={'ordering': ['fecha_inicio']},
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='target_food',
        ),
        migrations.AddField(
            model_name='promotion',
            name='detalle',
            field=models.TextField(blank=True, verbose_name='detalle de la promocion'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='promotion',
            name='fecha_inicio',
            field=models.DateTimeField(null=True, verbose_name='inicio de la promocion'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='image',
            field=models.ImageField(null=True, upload_to='promotions/', verbose_name='Afiche de promocion'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre para la Promocion'),
        ),
        migrations.CreateModel(
            name='PromoProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.PositiveIntegerField(verbose_name='Precio')),
                ('descuento', models.PositiveIntegerField(blank=True, default=0, verbose_name="% descuento (solo si tipo es = 'descuento')")),
                ('tipo', models.CharField(choices=[('descuento', 'Descuento%'), ('2x1', '2x1'), ('combo', 'Combo')], default='descuento', max_length=20, verbose_name='Tipo de promocion')),
                ('image', models.ImageField(blank=True, null=True, upload_to='promo_products/')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='cafeteria_app.promotion')),
            ],
        ),
    ]
