# Generated by Django 4.2.30 on 2026-06-26 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria_app', '0020_alter_promotion_options_remove_promotion_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, null=True, verbose_name='fin de la promocion'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='fecha_inicio',
            field=models.DateTimeField(blank=True, null=True, verbose_name='inicio de la promocion'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='promotions/', verbose_name='Afiche de promocion'),
        ),
    ]
