# Generated by Django 4.2.30 on 2026-06-26 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria_app', '0021_alter_promotion_fecha_fin_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PromoProduct',
        ),
        migrations.DeleteModel(
            name='Promotion',
        ),
    ]
