# Generated by Django 4.2.30 on 2026-06-27 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria_app', '0022_delete_promoproduct_delete_promotion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidoitem',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
